# Builder
FROM arm64v8/golang as builder

LABEL MAINTAINER Iamck <thanhson_it201@yahoo.com> (https://sonck201.github.io)

ENV CADVISOR_VERSION "v0.38.6"

RUN apt-get update && apt-get install -y git dmsetup && apt-get clean

RUN git clone -b ${CADVISOR_VERSION} https://github.com/google/cadvisor.git /go/src/github.com/google/cadvisor

WORKDIR /go/src/github.com/google/cadvisor

RUN make build

# Image for usage
FROM arm64v8/debian

LABEL MAINTAINER Iamck <thanhson_it201@yahoo.com> (https://sonck201.github.io)

COPY --from=builder /go/src/github.com/google/cadvisor/cadvisor /usr/bin/cadvisor

EXPOSE 8080

ENTRYPOINT ["/usr/bin/cadvisor", "-logtostderr"]
